version: '3.9'
services:
  demo-db:
    image: postgis/postgis:12-3.2
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: postgres   # password for the "postgres" superuser
    ports:
      - "5435:5432"
